import assert from 'node:assert/strict';
import {incomeEstimate,frequencyOf,paymentDate} from '../modules/income.js';
import {blankState} from '../modules/state.js';
import {createPortfolioEngine} from '../modules/portfolio.js';
import {buildHomeMetrics,nextMilestone} from '../modules/home-metrics.js';
import {validateLedger} from '../modules/validation.js';
import {demoState} from '../modules/demo.js';
import {createStoreZip,readStateFromBackupFile} from '../backup.js';

const now=new Date('2026-09-19T12:00:00Z');
const weekly={distributionFrequency:'weekly'};
const rows=Array.from({length:8},(_,i)=>({date:new Date(+now-i*7*86400000).toISOString().slice(0,10),amountUSD:40,sharesAtPayment:200}));
assert.equal(incomeEstimate(weekly,rows,[],400,now).payout,80,'additional shares must increase forecast');
assert.equal(incomeEstimate(weekly,rows,[],0,now).payout,0,'sold position must not forecast dividends');
assert.ok(Math.abs(incomeEstimate(weekly,rows,[],400,now).trend)<1e-9);
const beforeSplit=[{date:'2026-09-04',amountUSD:40,sharesAtPayment:200},{date:'2026-09-11',amountUSD:40,sharesAtPayment:200}];
const adjusted=incomeEstimate(weekly,beforeSplit,[{date:'2026-09-12',from:2,to:1}],100,now);
assert.equal(adjusted.perShare,.4);assert.equal(adjusted.payout,40,'reverse split preserves income');
const quarterly=frequencyOf({distributionFrequency:'quarterly'});
assert.equal(incomeEstimate({distributionFrequency:'quarterly'},[rows[0]],[],200,now).monthly,40/3);
assert.equal(paymentDate('2026-01-31',1,frequencyOf({distributionFrequency:'monthly'})).getDate(),28);
assert.equal(paymentDate('2026-01-31',2,frequencyOf({distributionFrequency:'monthly'})).getDate(),31);
assert.equal(paymentDate('2026-11-30',1,quarterly).getMonth(),1);
for(const [shares,target] of [[249,250],[250,500],[500,750],[750,1000],[1000,1000]])assert.equal(nextMilestone({currentTarget:1000,shares}).shares,target);
assert.equal(nextMilestone({currentTarget:1000,shares:1000}).reached,true);

const state=demoState(),original=JSON.stringify(state),engine=createPortfolioEngine(()=>state,()=>state.projects[0].id);
assert.deepEqual(validateLedger(state),[]);
const metrics=buildHomeMetrics(engine.totals().rows,state.dividends);
assert.ok(metrics.month.total>=metrics.month.actual);
const sold=engine.totals().rows.map(c=>({...c,shares:0,estimateReliable:false}));
assert.equal(buildHomeMetrics(sold,state.dividends).nextDividend,null);
assert.equal(buildHomeMetrics(sold,state.dividends).pace.monthly,0);
assert.equal(JSON.stringify(state),original,'read-only calculations must not mutate ledger');
const zip=createStoreZip([{name:'data/state.json',data:original}]);
const file={name:'test.zip',arrayBuffer:()=>zip.arrayBuffer()};
assert.deepEqual(await readStateFromBackupFile(file),state,'ZIP round trip');
const broken=new Uint8Array(await zip.arrayBuffer());broken[50]^=1;
await assert.rejects(readStateFromBackupFile({name:'bad.zip',arrayBuffer:async()=>broken.buffer}));
assert.ok(validateLedger({...state,trades:[{id:'bad',projectId:'missing',date:'bad'}]}).length);
console.log('Replacement QA: ownership, splits, frequencies, month-end, milestones, nonmutation, ZIP integrity PASS');
