import {test,expect} from '@playwright/test';
async function ledger(page,key='state'){return page.evaluate(key=>new Promise((resolve,reject)=>{const req=indexedDB.open('DividendOSDB_V4');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,get=db.transaction('kv','readonly').objectStore('kv').get(key);get.onsuccess=()=>{db.close();resolve(get.result);};};}),key);}
const replacement={format:'dividend-os-dividend-replacement-v1',scope:'all-dividends',symbol:'MSTY',rows:[{date:'2026-01-02',amountKRW:5003},{date:'2026-01-09',amountKRW:10007}]};
async function upload(page,file=replacement){await page.locator('#dividendReplacementInput').setInputFiles({name:'synthetic-receipts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(file))});}
async function setup(page){await page.goto('/');await expect(page.locator('#splashScreen')).toBeHidden();await page.locator('[data-page="projects"]').first().click();await page.locator('.record-center > summary').click();await page.locator('.manual-tools > summary').click();await page.locator('[data-add-trade]').click();await page.locator('#tradeForm [name="date"]').fill('2026-01-01');await page.locator('#tradeForm [name="shares"]').fill('10');await page.locator('#tradeForm [name="price"]').fill('10');await page.locator('#tradeForm button[type="submit"]').click();await expect(page.locator('#tradeForm')).toBeHidden();await page.locator('[data-quick-dividend]').click();await page.locator('#dividendForm [name="date"]').fill('2026-01-01');await page.locator('#dividendForm [name="amountUSD"]').fill('9.99');await page.locator('#dividendForm button.primary').click();await expect(page.locator('#dividendForm')).toBeHidden();}

test('배당 교체는 안전 사본·재시작·원화 원본·환율 변경·ZIP 복원을 보존한다',async({page},testInfo)=>{
 await setup(page);const before=await ledger(page);expect(before.trades).toHaveLength(1);await upload(page);await expect(page.locator('.modal-title')).toHaveText('전체 배당 교체 확인');await expect(page.locator('#modal')).toContainText('15,010원');await page.locator('#confirmDividendReplacement').click();await expect(page.locator('.toast')).toContainText('2건을 KRW 원본으로 교체');
 const after=await ledger(page),safety=await ledger(page,'safetyBackup');expect(after.trades).toEqual(before.trades);expect(after.projects).toEqual(before.projects);expect(after.dividends).toHaveLength(2);expect(after.dividends.map(row=>row.amountKRW)).toEqual([5003,10007]);expect(after.dividends.every(row=>row.amountUSD===0&&row.sharesAtPayment===0)).toBeTruthy();expect(safety.dividends).toEqual(before.dividends);
 await page.reload();await expect(page.locator('#splashScreen')).toBeHidden();await page.locator('[data-page="projects"]').first().click();await expect(page.locator('.cashflow-secondary')).toContainText('15,010원');await expect(page.locator('.cashflow-secondary')).toContainText('달러 금액 미확인');await expect(page.locator('.holding-row strong').first()).toHaveText('10주');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:testInfo.outputPath('currency-portfolio.png'),fullPage:true});
 await page.locator('[data-page="settings"]').first().click();const display=page.locator('details.settings-section').filter({has:page.locator('#displaySettingsForm')});await display.locator(':scope > summary').click();await page.locator('#displaySettingsForm [name="exchangeRate"]').fill('1500');await page.locator('#displaySettingsForm button[type="submit"]').click();expect((await ledger(page)).dividends).toEqual(after.dividends);
 await page.locator('[data-page="projects"]').first().click();await expect(page.locator('.cashflow-secondary')).toContainText('15,010원');await upload(page);await expect(page.locator('.toast')).toContainText('이미 같은 배당');expect((await ledger(page)).dividends).toEqual(after.dividends);
 await page.locator('[data-page="settings"]').first().click();const advanced=page.locator('details.settings-section').filter({has:page.locator('[data-backup]')});await advanced.locator(':scope > summary').click();await page.locator('[data-backup]').click();const downloadPromise=page.waitForEvent('download');await page.locator('[data-backup-download]').click();const download=await downloadPromise,path=testInfo.outputPath('synthetic-krw-backup.zip');await download.saveAs(path);
 await page.locator('#restoreInput').setInputFiles(path);await expect(page.locator('#confirmRestore')).toBeVisible();await page.locator('#confirmRestore').click();await expect(page.locator('.toast')).toContainText('백업을 복원');expect((await ledger(page)).dividends).toEqual(after.dividends);
});

test('잘못된 교체는 삭제하지 않고 달러 실제 금액은 역산 없이 저장한다',async({page})=>{
 await setup(page);const before=await ledger(page);await upload(page,{...replacement,rows:[replacement.rows[0],replacement.rows[0]]});await expect(page.locator('.toast')).toContainText('날짜·중복');expect((await ledger(page)).dividends).toEqual(before.dividends);
 await upload(page,{...replacement,currency:'USD',rows:[{date:'2026-01-02',amountUSD:12.34}]});await expect(page.locator('#modal')).toContainText('$12.34');await page.locator('#confirmDividendReplacement').click();await expect.poll(async()=>(await ledger(page)).dividends[0].amountUSD).toBe(12.34);expect((await ledger(page)).dividends[0].currency).toBe('USD');
});
