import {test,expect} from '@playwright/test';
const noAuth=`export async function initGoogleAuth(){};export async function logoutGoogle(){};export async function getGoogleIdToken(){return null;}export async function getCloudDocument(){return null;}export async function getLegacyCloudDocument(){return null;}export async function saveCloudDocument(){return {revision:1};}export async function subscribeCloudDocument(){return ()=>{};}`;
async function ledger(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('DividendOSDB_V4');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,q=db.transaction('kv').objectStore('kv').get('state');q.onsuccess=()=>{db.close();resolve(q.result);};};}));}
async function manual(page,kind){for(const s of ['.record-center','.manual-tools'])if(await page.locator(s).getAttribute('open')===null)await page.locator(s+' > summary').click();await page.locator(`[data-add-${kind}]`).click();}
async function select(page,p){await page.locator('[data-page="projects"]').first().click();await page.locator(`[data-portfolio-group="${p.category==='highYield'?'highYield':'dividend'}"]`).click();if(await page.locator('[data-project-select]').count())await page.locator('[data-project-select]').selectOption(p.id);else if(await page.locator(`[data-select-project="${p.id}"]`).count())await page.locator(`[data-select-project="${p.id}"]`).click();await expect(page.locator('.project-symbol')).toHaveText(p.symbol);}
async function trade(page,date,shares,type='buy',buyType='direct'){await manual(page,'trade');await page.locator('#tradeForm [name="date"]').fill(date);await page.locator('#tradeForm [name="shares"]').fill(String(shares));await page.locator('#tradeForm [name="price"]').fill('10');await page.locator('#tradeForm [name="type"]').selectOption(type);if(type==='buy')await page.locator('#tradeForm [name="buyType"]').selectOption(buyType);await page.locator('#tradeForm button[type="submit"]').click();}
async function dividend(page,date,amount,currency='USD',next=false){await manual(page,'dividend');await page.locator('#dividendForm [name="date"]').fill(date);await page.locator('#dividendForm [name="currency"]').selectOption(currency);await page.locator('#dividendForm [name="amountUSD"]').fill(String(amount));await page.locator(next?'#dividendForm [name="next"]':'#dividendForm button.primary').click();}
async function edit(page,row){if(await page.locator('.record-center').getAttribute('open')===null)await page.locator('.record-center > summary').click();await page.locator(`.records-list [data-view-record="dividend:${row.id}"]`).click();const manage=page.locator('.record-manage > summary');if(await manage.count())await manage.click();await page.locator(`[data-edit-record="dividend:${row.id}"]`).click();}
async function close(page){await page.locator('[data-close-modal]').first().click();if(await page.locator('[data-discard-modal]').count())await page.locator('[data-discard-modal]').click();}
async function advanced(page){await page.locator('[data-page="settings"]').first().click();const s=page.locator('details.settings-section').filter({has:page.locator('[data-backup]')});if(await s.getAttribute('open')===null)await s.locator(':scope > summary').click();}

for(const count of [8,9])test(`${count}종목 교차 입력·재투자·통화·수정·삭제·분류·오프라인·복원은 종목별 원장을 보존한다`,async({page,context},info)=>{
 test.skip(process.env.QA_HARD_UI!=='1','Explicit 8/9-stock hard QA');test.setTimeout(15*60_000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/modules/cloud-api.js',r=>r.fulfill({contentType:'application/javascript',body:noAuth}));await page.goto('/');await expect(page.locator('#splashScreen')).toBeHidden();await page.locator('[data-page="projects"]').first().click();
 for(const symbol of Array.from({length:count-1},(_,i)=>'QA'+String.fromCharCode(65+i))){await page.locator('[data-add-project]').click();await page.locator('#projectForm [name="symbol"]').fill(symbol);await page.locator('#projectForm [name="category"]').selectOption('highYield');await page.locator('#projectForm button[type="submit"]').click();await expect(page.locator('#projectForm')).toBeHidden();}
 console.log(info.project.name,count,'프로젝트 생성 완료');let projects=(await ledger(page)).projects;expect(projects).toHaveLength(count);const expected=new Map(projects.map(p=>[p.id,{shares:0,cents:0}]));
 for(let round=0;round<4;round++)for(let i=0;i<count;i++){const p=projects[(i+round)%count],e=expected.get(p.id),date=`2025-${String(round+1).padStart(2,'0')}-15`;await select(page,p);await trade(page,date,i+1,'buy',round===3?'reinvest':'direct');await expect(page.locator('#tradeForm')).toBeHidden();e.shares+=i+1;const cents=10000+round*100+i;await dividend(page,date,(cents/100).toFixed(2));await expect(page.locator('#dividendForm')).toBeHidden();e.cents+=cents;const s=await ledger(page);expect(s.trades.at(-1)).toMatchObject({projectId:p.id,shares:i+1});expect(s.dividends.at(-1)).toMatchObject({projectId:p.id,amountUSD:cents/100});await expect(page.locator('.holding-row strong').first()).toHaveText(`${e.shares}주`);console.log(info.project.name,count,p.symbol,'round',round,'입력 완료');}
 for(let i=0;i<count;i++){const p=projects[i],e=expected.get(p.id);await select(page,p);const before=await ledger(page);await dividend(page,'2025-06-01',0);await expect(page.locator('#dividendForm')).toBeVisible();expect((await ledger(page)).dividends).toEqual(before.dividends);await page.locator('#dividendForm [name="amountUSD"]').fill('1.001');await page.locator('#dividendForm button.primary').click();await expect(page.locator('#dividendForm')).toBeVisible();expect((await ledger(page)).dividends).toEqual(before.dividends);await close(page);
 await trade(page,'2025-06-01',e.shares+1,'sell');await expect(page.locator('.toast')).toContainText('많이 매도');expect((await ledger(page)).trades).toEqual(before.trades);await close(page);await dividend(page,'2025-06-01',1000+i,'KRW');await expect(page.locator('#dividendForm')).toBeHidden();
 const d=(await ledger(page)).dividends.filter(r=>r.projectId===p.id&&r.currency==='USD').at(-1);await edit(page,d);await page.locator('#dividendForm [name="amountUSD"]').fill('20.01');await page.locator('#dividendForm button.primary').click();await expect(page.locator('#dividendForm')).toBeHidden();e.cents+=2001-Math.round(d.amountUSD*100);const krw=(await ledger(page)).dividends.find(r=>r.projectId===p.id&&r.currency==='KRW');await edit(page,krw);await page.locator('[data-delete-from-edit]').click();await page.locator('#modalConfirm').click();await expect(page.locator('#modalConfirm')).toBeHidden();}

 const planEvidence=[];
 for(let i=0;i<count;i++){
  const p=projects[i],before=await ledger(page),useAmount=i+3;
  await select(page,p);
  await manual(page,'trade');await page.locator('#tradeForm [name="date"]').fill('2025-07-01');await page.locator('#tradeForm [name="shares"]').fill('10000');await page.locator('#tradeForm [name="price"]').fill('10');await page.locator('#tradeForm [name="buyType"]').selectOption('reinvest');await page.locator('#tradeForm button[type="submit"]').click();await expect(page.locator('.toast')).toContainText('배당 잔액이 부족');expect((await ledger(page)).trades).toEqual(before.trades);await close(page);
  for(const price of [20,1]){
   for(const name of ['record-center','manual-tools'])if(await page.locator('.'+name).getAttribute('open')===null)await page.locator('.'+name+' > summary').click();
   await page.locator('[data-edit-price]').click();await page.locator('#priceForm [name="price"]').fill(String(price));await page.locator('#priceForm button[type="submit"]').click();await expect(page.locator('#priceForm')).toBeHidden();
   await expect(page.locator('#page-projects .dividend-plan-notice')).toContainText(price===20?'플러스':'마이너스');await page.locator('#page-projects .dividend-plan-notice [data-dividend-mode]').click();await page.locator('#modalConfirm').click();await expect(page.locator('#modalBackdrop')).not.toHaveClass(/show/);
   if(price===20){
    await page.locator('#page-projects [data-add-withdrawal]').click();await page.locator('#withdrawalForm [name="date"]').fill('2025-07-01');await page.locator('#withdrawalForm [name="amountUSD"]').fill(String(useAmount));await page.locator('#withdrawalForm [name="destination"]').selectOption(['isa','otherDividend','living','other'][i%4]);await page.locator('#withdrawalForm [name="note"]').fill(p.symbol+' 전용 사용');await page.locator('#withdrawalForm button[type="submit"]').click();await expect(page.locator('#withdrawalForm')).toBeHidden();
    const details=page.locator('#page-projects .dividend-use-details');if(await details.getAttribute('open')===null)await details.locator(':scope > summary').click();
    const row=(await ledger(page)).cashAdjustments.filter(r=>r.projectId===p.id).at(-1);await details.locator(`[data-view-record="cash:${row.id}"]`).click();await page.locator('.record-manage > summary').click();await page.locator(`[data-edit-record="cash:${row.id}"]`).click();await page.locator('#withdrawalForm [name="amountUSD"]').fill(String(useAmount+1));await page.locator('#withdrawalForm button[type="submit"]').click();await expect(page.locator('#withdrawalForm')).toBeHidden();
    const reopened=page.locator('#page-projects .dividend-use-details');if(await reopened.getAttribute('open')===null)await reopened.locator(':scope > summary').click();await reopened.locator(`[data-view-record="cash:${row.id}"]`).click();await page.locator('.record-manage > summary').click();await page.locator(`[data-edit-record="cash:${row.id}"]`).click();await page.locator('[data-delete-from-edit]').click();await page.locator('#modalConfirm').click();await expect(page.locator('#modalConfirm')).toBeHidden();expect((await ledger(page)).cashAdjustments.some(r=>r.id===row.id)).toBe(false);
    await page.locator('#page-projects [data-add-withdrawal]').click();await page.locator('#withdrawalForm [name="date"]').fill('2025-07-01');await page.locator('#withdrawalForm [name="amountUSD"]').fill(String(useAmount));await page.locator('#withdrawalForm [name="destination"]').selectOption(['isa','otherDividend','living','other'][i%4]);await page.locator('#withdrawalForm button[type="submit"]').click();await expect(page.locator('#withdrawalForm')).toBeHidden();
   }
  }
  await page.locator('[data-project-settings]').click();await page.locator('#projectForm [name="targetUnits"]').fill(String(expected.get(p.id).shares));await page.locator('#projectForm button[type="submit"]').click();await expect(page.locator('#projectForm')).toBeHidden();await expect(page.locator('.dividend-management .recovery-hero')).toContainText('남은 회수 원금');
  const after=await ledger(page);expect(after.trades).toEqual(before.trades);expect(after.dividends).toEqual(before.dividends);expect(after.projects.find(x=>x.id===p.id).dividendPlan.history).toHaveLength(2);
  for(const other of projects.filter(x=>x.id!==p.id)){expect(after.projects.find(x=>x.id===other.id)).toEqual(before.projects.find(x=>x.id===other.id));expect(after.cashAdjustments.filter(x=>x.projectId===other.id)).toEqual(before.cashAdjustments.filter(x=>x.projectId===other.id));}
  const calculated=await page.evaluate(async id=>{const {storageGet}=await import('/storage.js'),{createPortfolioEngine}=await import('/modules/portfolio.js'),{projectRecovery}=await import('/modules/dividend-plan.js');const state=await storageGet('state'),p=state.projects.find(p=>p.id===id),c=createPortfolioEngine(()=>state,()=>id).computeProject(p);return {shares:c.shares,dividendAvailable:c.dividendAvailable,reinvestCost:c.reinvestAmount,recovery:projectRecovery(c)};},p.id);
  const reinvestCost=after.trades.filter(r=>r.projectId===p.id&&r.buyType==='reinvest').reduce((a,r)=>a+r.shares*r.price,0);expect(calculated.dividendAvailable).toBeCloseTo(expected.get(p.id).cents/100-reinvestCost-useAmount,6);expect(calculated.recovery.total).toBe(useAmount);expect(calculated.recovery.basis).toBe(after.trades.filter(r=>r.projectId===p.id&&r.buyType==='direct').reduce((a,r)=>a+r.shares*r.price,0));
  planEvidence.push({symbol:p.symbol,shares:calculated.shares,usdDividends:expected.get(p.id).cents/100,reinvestment:reinvestCost,externalUse:useAmount,available:calculated.dividendAvailable,basis:calculated.recovery.basis,remaining:calculated.recovery.remaining,mode:'reinvest',history:2});console.log(info.project.name,count,p.symbol,'개별 입력·수정·삭제·전환·회수 PASS');
 }
 await info.attach('per-project-plan-evidence',{body:JSON.stringify(planEvidence,null,2),contentType:'application/json'});
 for(let i=0;i<count;i++){const p=projects[i];await select(page,p);await page.locator('[data-project-settings]').click();await page.locator('#projectForm [name="category"]').selectOption(i<3?'growth':'highYield');await page.locator('#projectForm .form-advanced > summary').click();await page.locator('#projectForm [name="distributionFrequency"]').selectOption(['weekly','monthly','quarterly'][i%3]);await page.locator('#projectForm button[type="submit"]').click();await expect(page.locator('#projectForm')).toBeHidden();projects=(await ledger(page)).projects;}
 await context.setOffline(true);await select(page,projects[0]);await dividend(page,'2025-07-01','3.21','USD',true);await expect(page.locator('#dividendForm')).toBeVisible();await expect(page.locator('#dividendForm [name="amountUSD"]')).toHaveValue('0');await close(page);expected.get(projects[0].id).cents+=321;await context.setOffline(false);
 const saved=await ledger(page);for(const p of projects){const e=expected.get(p.id);expect(saved.trades.filter(r=>r.projectId===p.id).reduce((s,r)=>s+r.shares,0)).toBe(e.shares);expect(saved.dividends.filter(r=>r.projectId===p.id).reduce((s,r)=>s+Math.round(r.amountUSD*100),0)).toBe(e.cents);expect(saved.dividends.some(r=>r.projectId===p.id&&r.currency==='KRW')).toBe(false);}
 await page.reload();await expect(page.locator('#splashScreen')).toBeHidden();expect((await ledger(page)).trades).toEqual(saved.trades);expect((await ledger(page)).dividends).toEqual(saved.dividends);for(const p of projects){await select(page,p);await expect(page.locator('.holding-row strong').first()).toHaveText(`${expected.get(p.id).shares}주`);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);}
 await advanced(page);await page.locator('[data-backup]').click();const downloading=page.waitForEvent('download');await page.locator('[data-backup-download]').click();const file=info.outputPath('synthetic-many-projects.zip');await(await downloading).saveAs(file);await close(page);await select(page,projects[count-1]);await trade(page,'2025-08-01',1);await expect(page.locator('#tradeForm')).toBeHidden();await page.locator('#restoreInput').setInputFiles(file);await page.locator('#confirmRestore').click();await expect(page.locator('#confirmRestore')).toBeHidden();const restored=await ledger(page);expect(restored.projects).toEqual(saved.projects);expect(restored.trades).toEqual(saved.trades);expect(restored.dividends).toEqual(saved.dividends);expect(restored.cashAdjustments).toEqual(saved.cashAdjustments);expect(errors).toEqual([]);await info.attach('many-project-evidence',{body:JSON.stringify({scope:'isolated synthetic localhost UI',projects:count,expected:[...expected],trades:saved.trades.length,dividends:saved.dividends.length,pageErrors:errors}),contentType:'application/json'});await page.screenshot({path:info.outputPath('many-projects.png'),fullPage:true});
});

