import {test,expect} from '@playwright/test';
const noAuth=`export async function initGoogleAuth(){};export async function logoutGoogle(){};export async function getGoogleIdToken(){return null;}export async function getCloudDocument(){return null;}export async function getLegacyCloudDocument(){return null;}export async function saveCloudDocument(){return {revision:1};}export async function subscribeCloudDocument(){return ()=>{};}`;
async function ledger(page){return page.evaluate(async()=>{const {storageGet}=await import('/storage.js');return storageGet('state');});}
async function manual(page,kind){for(const s of ['.record-center','.manual-tools'])if(await page.locator(s).getAttribute('open')===null)await page.locator(s+' > summary').click();await page.locator(`[data-add-${kind}]`).click();}
async function select(page,p){await page.locator('[data-page="projects"]').first().click();await page.locator('[data-portfolio-group="highYield"]').click();if(await page.locator('[data-project-select]').count())await page.locator('[data-project-select]').selectOption(p.id);else await page.locator(`[data-select-project="${p.id}"]`).click();await expect(page.locator('.project-symbol')).toHaveText(p.symbol);}
for(const count of [8,9])test(`${count}종목 30년 고액 배당을 실제 입력 폼으로 저장·재시작 검증`,async({page},info)=>{
 test.skip(process.env.QA_HIGH_LIFETIME_UI!=='1','Explicit 30-year high-value UI QA');test.setTimeout(120*60_000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2056-01-02T00:00:00Z'));await page.route('**/modules/cloud-api.js',r=>r.fulfill({contentType:'application/javascript',body:noAuth}));await page.goto('/');await expect(page.locator('#splashScreen')).toBeHidden();await page.locator('[data-page="projects"]').first().click();
 for(let i=1;i<count;i++){await page.locator('[data-add-project]').click();await page.locator('#projectForm [name="symbol"]').fill('HLT'+String(i).padStart(2,'0'));await page.locator('#projectForm [name="category"]').selectOption('highYield');await page.locator('#projectForm button[type="submit"]').click();await expect(page.locator('#projectForm')).toBeHidden();}
 const projects=(await ledger(page)).projects,evidence=[];
 for(let i=0;i<count;i++){
  const p=projects[i];await select(page,p);await manual(page,'trade');await page.locator('#tradeForm [name="date"]').fill('2026-01-01');await page.locator('#tradeForm [name="shares"]').fill('10000');await page.locator('#tradeForm [name="price"]').fill(String(25+i));await page.locator('#tradeForm button[type="submit"]').click();await expect(page.locator('#tradeForm')).toBeHidden();
  await manual(page,'dividend');let cents=0,maxMs=0;
  for(let y=2026;y<=2055;y++){
   const rows=Array.from({length:12},(_,m)=>({date:`${y}-${String(m+1).padStart(2,'0')}-15`,cents:100000+i*250000+(y-2026)*12000+(m+1)*101}));cents+=rows.reduce((a,r)=>a+r.cents,0);
   const timings=await page.evaluate(async rows=>{
    const delays=[];for(const row of rows){const form=document.querySelector('#dividendForm');if(!form)throw Error('배당 폼이 사라짐');for(const [name,value] of Object.entries({date:row.date,amountUSD:(row.cents/100).toFixed(2)})){const input=form.elements.namedItem(name);input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}const started=performance.now();form.querySelector('[name="next"]').click();while(document.querySelector('#dividendForm')===form){if(performance.now()-started>60000)throw Error('저장 60초 초과 '+row.date);await new Promise(r=>setTimeout(r,10));}delays.push(performance.now()-started);}return delays;
   },rows);maxMs=Math.max(maxMs,...timings);
   const saved=await ledger(page),actual=saved.dividends.filter(r=>r.projectId===p.id);expect(actual).toHaveLength((y-2025)*12);expect(actual.reduce((a,r)=>a+Math.round(r.amountUSD*100),0)).toBe(cents);console.log(count,p.symbol,y,'입력 폼 저장 PASS',actual.length,'건',cents/100,'USD',Math.round(maxMs),'ms');
  }
  await page.locator('[data-close-modal]').first().click();
  const calc=await page.evaluate(async id=>{const {storageGet}=await import('/storage.js'),{createPortfolioEngine}=await import('/modules/portfolio.js');const s=await storageGet('state'),c=createPortfolioEngine(()=>s,()=>id).computeProject(id);return {shares:c.shares,dividends:c.dividendsTotal,available:c.dividendAvailable,min:c.minDividendBalance};},p.id);
  expect(calc.shares).toBe(10000);expect(calc.dividends).toBeCloseTo(cents/100,5);expect(calc.available).toBeCloseTo(cents/100,5);expect(calc.min).toBeGreaterThanOrEqual(0);evidence.push({symbol:p.symbol,years:30,records:360,usd:cents/100,maxSaveMs:Math.round(maxMs)});
 }
 const before=await ledger(page);await page.reload();await expect(page.locator('#splashScreen')).toBeHidden();const after=await ledger(page);expect(after.dividends).toEqual(before.dividends);expect(after.trades).toEqual(before.trades);expect(errors).toEqual([]);for(const p of projects){await select(page,p);await expect(page.locator('.holding-row strong').first()).toHaveText('10,000주');expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);}
 await info.attach('30-year-large-ui-evidence',{body:JSON.stringify({count,totalRows:before.dividends.length,evidence,pageErrors:errors},null,2),contentType:'application/json'});await page.screenshot({path:info.outputPath('30-year.png'),fullPage:true});
});
