import {test,expect} from '@playwright/test';
test.use({serviceWorkers:'block'});
async function settings(page){await page.goto('/?demo=1');await expect(page.locator('#splashScreen')).toBeHidden();await page.locator('[data-page="settings"]').first().click();}
test('설정 저장 후 펼침과 현재 스크롤 위치를 유지한다',async({page})=>{
 await settings(page);const section=page.locator('.settings-section').filter({has:page.locator('#dividendSettingsForm')});await section.locator(':scope > summary').click();await page.locator('[name="targetMonthlyDividend"]').fill('777');await page.locator('#dividendSettingsForm button').scrollIntoViewIfNeeded();const before=await page.evaluate(()=>scrollY);await page.locator('#dividendSettingsForm button').click();await expect(page.locator('.toast')).toContainText('배당 기준을 저장');await expect(section).toHaveAttribute('open','');await expect(page.locator('[name="targetMonthlyDividend"]')).toHaveValue('777');expect(Math.abs((await page.evaluate(()=>scrollY))-before)).toBeLessThan(3);
});
test('백업 창에서 시스템 뒤로가기는 설정으로 돌아오며 파일을 생성하지 않는다',async({page})=>{
 await settings(page);const section=page.locator('.settings-section').filter({has:page.locator('[data-backup]')});await section.locator(':scope > summary').click();await page.locator('[data-backup]').click();await expect(page.locator('[data-backup-save]')).toBeVisible();await page.evaluate(()=>history.back());await expect(page.locator('#modalBackdrop')).not.toHaveClass(/show/);await expect(page.locator('#page-settings')).toBeVisible();await expect(section).toHaveAttribute('open','');await page.evaluate(()=>history.back());await expect(section).not.toHaveAttribute('open','');await expect(page.locator('#page-settings')).toBeVisible();await page.evaluate(()=>history.back());await expect(page.locator('#page-home')).toBeVisible();
});
test('뒤로가기를 눌러도 작성 중인 종목 설정을 즉시 버리지 않는다',async({page})=>{
 await settings(page);const section=page.locator('.settings-section').filter({has:page.locator('.settings-project-list')});await section.locator(':scope > summary').click();await section.locator('[data-settings-project]').first().click();await page.locator('#projectForm .form-advanced > summary').click();await page.locator('#projectForm [name="name"]').fill('아직 저장 안 함');await page.evaluate(()=>history.back());await expect(page.locator('.modal-unsaved')).toBeVisible();await expect(page.locator('#projectForm [name="name"]')).toHaveValue('아직 저장 안 함');await page.locator('[data-keep-modal]').click();await expect(page.locator('#modalBackdrop')).toHaveClass(/show/);
});
