import assert from 'node:assert/strict';
import {blankState} from '../modules/state.js';
import {createPortfolioEngine} from '../modules/portfolio.js';
import {dividendPlanStatus,projectRecovery,hasNewDividendDeficit} from '../modules/dividend-plan.js';
import {decodeAppState} from '../modules/state-decoder.js';
import {rebuildProjectFromTossSource,tossCandidateToTrade} from '../modules/toss.js';
import {buildCsvExports,createStoreZip,readStateFromBackupFile} from '../backup.js';
const state=blankState(),p=state.projects[0];p.currentPrice=9;p.priceUpdatedAt=new Date().toISOString();p.targetUnits=1000;
state.trades=[{id:'first',projectId:p.id,date:'2025-01-01',type:'buy',buyType:'direct',shares:100,price:10}];
state.dividends=[{id:'income',projectId:p.id,date:'2025-01-02',amountUSD:100}];
state.trades.push({id:'reinvest',projectId:p.id,date:'2025-01-03',type:'buy',buyType:'reinvest',shares:5,price:10,feeUSD:1});
const engine=createPortfolioEngine(()=>state,()=>p.id),calc=()=>engine.computeProject(p);
assert.equal(calc().dividendAvailable,49);assert.equal(calc().cashLedger.at(-1).balance,undefined);
assert.equal(calc().cashLedger.reduce((sum,row)=>sum+row.amountUSD,0),49,'reinvestment cash ledger includes fees');
assert.equal(projectRecovery(calc()).basis,1000);assert.equal(projectRecovery(calc()).total,0);
assert.equal(dividendPlanStatus(calc()).suggested,null);p.currentPrice=11;assert.equal(dividendPlanStatus(calc()).suggested,'outside');
p.dividendPlan={mode:'outside',history:[{mode:'outside',confirmedAt:new Date().toISOString()}]};
const original=structuredClone(state.trades);state.cashAdjustments.push({id:'use',projectId:p.id,date:'2025-01-04',amountUSD:-30,purpose:'dividendUse',destination:'isa'});
assert.equal(calc().dividendAvailable,19);assert.deepEqual(state.trades,original);
assert.equal(projectRecovery(calc()).total,30);assert.equal(projectRecovery(calc()).remaining,970);
p.currentPrice=9;assert.equal(dividendPlanStatus(calc()).suggested,'reinvest');
p.currentPrice=calc().purchaseBasis/calc().shares;assert.equal(dividendPlanStatus(calc()).suggested,null,'zero keeps mode');
p.priceUpdatedAt='2020-01-01';p.currentPrice=9;assert.equal(dividendPlanStatus(calc()).suggested,null,'stale prices cannot suggest');
p.priceUpdatedAt=new Date().toISOString();p.currentPrice=0;assert.equal(dividendPlanStatus(calc()).suggested,null,'missing prices cannot suggest');
p.currentPrice=10;
state.dividends.push({id:'roc',projectId:p.id,date:'2025-01-05',amountUSD:1,rocAmountUSD:1});
assert.equal(calc().priceUnrealized,-1,'ROC cannot flip price-only loss into profit');assert.equal(calc().unrealized,0);
const before=calc();state.cashAdjustments.push({id:'too-old',projectId:p.id,date:'2024-12-01',amountUSD:-10,purpose:'dividendUse',destination:'living'});
assert.equal(hasNewDividendDeficit(before,calc()),true,'backdated spending before receipt rejected');state.cashAdjustments.pop();
state.trades.push({id:'extra',projectId:p.id,date:'2025-01-06',type:'buy',buyType:'direct',shares:10,price:10});
assert.equal(projectRecovery(calc()).basis,1100,'fresh contribution increases target');
state.trades.push({id:'goal',projectId:p.id,date:'2025-01-07',type:'buy',buyType:'direct',shares:885,price:10});
assert.ok(calc().targetReachedDate);assert.equal(projectRecovery(calc()).total,30,'goal does not reset recovered dividends');
p.recovery={locked:true,basis:300,startDate:'2025-01-04',targetReachedDate:'2025-01-07',calculatedBasisAtLock:300,confirmedAt:'2025-01-07T00:00:00Z',method:'withdrawnOnly'};
assert.equal(projectRecovery(calc()).basis,300,'legacy locked basis retained');assert.equal(engine.recoveryStats(calc()).total,30);
assert.deepEqual(decodeAppState(state).projects[0].dividendPlan,p.dividendPlan);
assert.equal(decodeAppState(state).cashAdjustments[0].destination,'isa');
const order={id:'broker-one',symbol:p.symbol,date:'2025-02-01',currency:'USD',type:'buy',shares:1,price:10,accountId:'account'};
const imported=tossCandidateToTrade(order,{projectId:p.id,id:'imported'});imported.dividendFunding={amountUSD:10,sourceFingerprint:imported.source.sourceFingerprint};
const rebuild=()=>rebuildProjectFromTossSource({project:p,sourceLedger:{orders:[order]},currentTrades:[imported],currentDividends:state.dividends,capabilities:{dividends:false},syncStatus:'complete'});
assert.deepEqual(rebuild().trades[0].dividendFunding,imported.dividendFunding);
order.price=11;assert.equal(rebuild().trades[0].dividendFunding,undefined,'changed broker originals require funding reconfirmation');
const zip=createStoreZip([{name:'data/state.json',data:JSON.stringify(state)}]);const file=Object.assign(zip,{name:'plan.zip'});
const restored=await readStateFromBackupFile(file);assert.equal(restored.projects[0].dividendPlan.mode,'outside');assert.equal(restored.cashAdjustments[0].destination,'isa');
const invalid=structuredClone(state);invalid.projects[0].dividendPlan.history[0].confirmedAt='bad';assert.throws(()=>decodeAppState(invalid));
const exportState=structuredClone(state);exportState.trades.push(imported);
const exports=buildCsvExports(exportState),usesCSV=exports.find(row=>row.name==='cash-adjustments.csv').data;
assert.match(usesCSV,/dividendUse,isa/);assert.match(usesCSV,/-30/);
const buysCSV=exports.find(row=>row.name==='trades.csv').data;assert.match(buysCSV,/dividendFundingUSD,fundingStatus/);assert.match(buysCSV,/,10,confirmed,/);
assert.match(exports.find(row=>row.name==='goals.csv').data,/dividendUseMode/);assert.match(exports.find(row=>row.name==='goals.csv').data,/,outside/);
console.log('Dividend plan QA PASS: cash conservation, ROC, stale/zero prices, early/locked recovery, goal continuity, Toss funding preservation, ZIP restore');
