import assert from 'node:assert/strict';
import {parseDividendReplacement,reportingDividends,dividendCashBreakdown} from '../modules/finance.js';
import {blankState,migrate} from '../modules/state.js';
import {validateLedger} from '../modules/validation.js';
import {createPortfolioEngine} from '../modules/portfolio.js';
import {createFormatters} from '../modules/format.js';
import {buildDividendAnalytics} from '../modules/dividend-analytics.js';
import {buildHomeMetrics} from '../modules/home-metrics.js';
import {createStoreZip,readStateFromBackupFile,buildCsvExports} from '../backup.js';
const file={format:'dividend-os-dividend-replacement-v1',scope:'all-dividends',symbol:'MSTY',rows:[{date:'2026-01-09',amountKRW:10007},{date:'2026-01-02',amountKRW:5003}]};
const parsed=parseDividendReplacement(file,'2026-02-01');assert.equal(parsed.totalKRW,15010);assert.equal(parsed.rows[0].date,'2026-01-02');
for(const rows of [[{date:'2026-02-30',amountKRW:1}],[{date:'2027-01-01',amountKRW:1}],[{date:'2026-01-01',amountKRW:1.1}], [...file.rows,file.rows[0]], [{date:'2026-01-01',amountKRW:Infinity}]])assert.throws(()=>parseDividendReplacement({...file,rows},'2026-02-01'));
const usd=parseDividendReplacement({...file,currency:'USD',rows:[{date:'2026-01-02',amountUSD:12.34}]},'2026-02-01');assert.equal(usd.totalUSD,12.34);
const state=blankState(),project=state.projects[0];project.currentPrice=12;
state.trades=[{id:'buy',projectId:project.id,date:'2026-01-01',type:'buy',buyType:'direct',shares:10,price:10}];
state.dividends=parsed.rows.map((row,index)=>({...row,id:'div-'+index,projectId:project.id,currency:'KRW',amountUSD:0,sharesAtPayment:0}));
const original=JSON.stringify(state);assert.deepEqual(validateLedger(state),[]);
const engine=createPortfolioEngine(()=>state,()=>project.id),calc=engine.computeProject(project);
assert.equal(calc.shares,10);assert.equal(calc.usdDividendsTotal,0);assert.equal(calc.dividendAvailable,0);assert.equal(calc.totalReturn,null);assert.equal(calc.analytics.trailingYoc,null);assert.equal(calc.postedDividends.length,2);
const formatter=createFormatters(()=>state);assert.equal(formatter.fmtDividend(state.dividends[0]),'5,003원');
const report=reportingDividends(state.dividends,state.settings.exchangeRate);
assert.equal(Math.round(buildHomeMetrics([calc],report,new Date('2026-01-20T12:00:00')).month.actual*state.settings.exchangeRate),15010);
state.settings.exchangeRate=1500;assert.equal(formatter.fmtDividend(state.dividends[0]),'5,003원');assert.equal(engine.computeProject(project).dividendAvailable,0);
state.settings.exchangeRate=1370;assert.equal(JSON.stringify(state),original,'reporting and calculations must not mutate receipt currency or source amounts');
const zip=createStoreZip([{name:'data/state.json',data:JSON.stringify(state)}]);assert.deepEqual(migrate(await readStateFromBackupFile({name:'mixed.zip',arrayBuffer:()=>zip.arrayBuffer()})),migrate(state));
const csv=buildCsvExports(state).find(row=>row.name==='dividends.csv').data;assert.match(csv,/amountKRW/);assert.match(csv,/KRW/);assert.match(csv,/5003/);
assert.equal(dividendCashBreakdown({...state.dividends[0],amountUSD:999}).netUSD,0,'KRW-only records cannot fund USD even with a contradictory legacy value');
assert.ok(validateLedger({...state,dividends:[{...state.dividends[0],amountUSD:999}]}).length);
console.log('Dividend currency PASS: strict replacement validation, immutable KRW, unconverted USD cash, home totals and lossless ZIP/CSV');

const gaps=buildDividendAnalytics({},[{date:'2019-01-01',amountUSD:2,sharesAtPayment:1},{date:'2021-01-01',amountUSD:1,sharesAtPayment:1}],[],1,'2026-01-01');assert.equal(gaps.annualDpsChange,null);assert.equal(gaps.cutCount,0,'missing years are not a verified dividend cut');
