import assert from 'node:assert/strict';
import {accountScopeChanged,buildTossSync,disconnectedTossState,normalizeTossOrder,mergeTossCandidates,mergeTossCorrectionCandidates,mergeTossDividendCandidates,mergeTossSourceLedger,nextTossSyncFrom,normalizeTossDividend,tossCandidateToDividend,tossCandidateToTrade,tossSyncProgress} from '../modules/toss.js';
const row={id:'order-1',symbol:'MSTY',date:'2026-01-01',side:'BUY',shares:2,price:10,currency:'USD'};
assert.equal(normalizeTossOrder(row).shares,2);
for(const bad of [{...row,shares:0},{...row,price:Infinity},{...row,date:'2026-02-30'},{...row,symbol:'<img>'}])assert.equal(normalizeTossOrder(bad),null);
const result=buildTossSync({orders:[row,row,{...row,id:'order-2',currency:'KRW'}],holdings:[{symbol:'MSTY',shares:3,currency:'USD'}]},{appPositions:[{symbol:'MSTY',shares:2}]});
assert.equal(result.candidates.length,1);
assert.equal(result.unsupportedCurrencyCount,1);
assert.equal(result.comparisons[0].difference,1);
assert.equal(mergeTossCandidates(result.candidates,result.candidates).length,1);
const manualConflict=buildTossSync({orders:[row]},{existingTrades:[{id:'manual-1',symbol:'MSTY',date:'2026-01-01',type:'buy',shares:2,price:10}]});
assert.equal(manualConflict.candidates.length,1,'similar manual rows require user review instead of silent suppression');
assert.equal(manualConflict.candidates[0].possibleManualDuplicate,true);
assert.deepEqual(manualConflict.candidates[0].manualMatchIds,['manual-1']);
const ledger1=mergeTossSourceLedger({}, {orders:[row],dividends:[{id:'div-1',symbol:'MSTY',date:'2026-01-08',netAmount:12.34,currency:'USD'}]},'2026-01-09T00:00:00Z');
assert.equal(ledger1.orders.length,1);
assert.equal(ledger1.dividends.length,1);
assert.equal(normalizeTossDividend({id:'div-1',symbol:'MSTY',date:'2026-01-08',netAmount:12.34,currency:'USD'}).amountUSD,12.34);
const ledger2=mergeTossSourceLedger(ledger1,{orders:[],dividends:[]},'2026-01-10T00:00:00Z');
assert.equal(ledger2.orders.length,1,'a later empty/disconnected response must not erase source history');
assert.equal(ledger2.dividends.length,1,'stored dividends must survive later gaps');
const ledgerSame=mergeTossSourceLedger(ledger1,{orders:[row],dividends:[]},'2026-01-10T12:00:00Z');
assert.equal(ledgerSame.orders[0].revisionCount,1,'replayed identical responses must not create revisions');
const ledgerChanged=mergeTossSourceLedger(ledger1,{orders:[{...row,price:11}],dividends:[]},'2026-01-11T00:00:00Z');
assert.equal(ledgerChanged.orders[0].revisionCount,2);
assert.equal(ledgerChanged.orders[0].lastChangedAt,'2026-01-11T00:00:00Z');
assert.equal(ledgerChanged.orders[0].revisions.length,1);
assert.equal(ledgerChanged.orders[0].revisions[0].price,10);
const dividendSnapshot={dividends:[{id:'div-1',symbol:'MSTY',date:'2026-01-08',netAmount:12.34,currency:'USD'}]};
const dividendSync=buildTossSync(dividendSnapshot,{existingDividends:[]});
assert.equal(dividendSync.dividendCandidates.length,1);
const manualDividendConflict=buildTossSync(dividendSnapshot,{existingDividends:[{id:'manual-div',symbol:'MSTY',date:'2026-01-08',amountUSD:12.34}]});
assert.equal(manualDividendConflict.dividendCandidates.length,1,'matching manual dividend must remain an unchecked review candidate');
assert.equal(manualDividendConflict.dividendCandidates[0].possibleManualDuplicate,true);
assert.equal(mergeTossDividendCandidates(dividendSync.dividendCandidates,dividendSync.dividendCandidates).length,1);
const approved=tossCandidateToDividend(dividendSync.dividendCandidates[0],{projectId:'p-msty',id:'d-approved',sharesAtPayment:100});
assert.equal(approved.source.externalId,'div-1');
assert.equal(approved.sharesAtPayment,100);
assert.equal(buildTossSync(dividendSnapshot,{existingDividends:[approved]}).dividendCandidates.length,0,'an approved Toss dividend must not return on the next sync');
const sameDaySnapshot={dividends:[
  {id:'same-1',symbol:'MSTY',date:'2026-01-15',netAmount:10,currency:'USD'},
  {id:'same-2',symbol:'MSTY',date:'2026-01-15',netAmount:10,currency:'USD'}
]};
const sameDay=buildTossSync(sameDaySnapshot,{existingDividends:[{symbol:'MSTY',date:'2026-01-15',amountUSD:10}]});
assert.equal(sameDay.matchedExistingDividendCount,1);
assert.equal(sameDay.dividendCandidates.length,2,'no Toss payment may be silently removed by a manual match');
assert.equal(sameDay.dividendCandidates.filter(row=>row.possibleManualDuplicate).length,1,'one manual record flags only one same-day Toss payment');
const multiAccount=buildTossSync({
  orders:[{...row,id:'shared-order',accountId:'acct-1',securityId:'US-MSTY',market:'NASDAQ'},{...row,id:'shared-order',accountId:'acct-2',securityId:'US-MSTY',market:'NASDAQ'}],
  holdings:[{symbol:'MSTY',shares:2,currency:'USD',accountId:'acct-1',securityId:'US-MSTY',market:'NASDAQ'},{symbol:'MSTY',shares:3,currency:'USD',accountId:'acct-2',securityId:'US-MSTY',market:'NASDAQ'}]
},{appPositions:[{symbol:'MSTY',assetKey:'toss:NASDAQ:US-MSTY',shares:5}]});
assert.equal(multiAccount.candidates.length,2,'same order id from two accounts must remain distinct');
assert.notEqual(multiAccount.candidates[0].externalId,multiAccount.candidates[1].externalId);
assert.equal(mergeTossCandidates(multiAccount.candidates,multiAccount.candidates).length,2,'normalizing linked candidates again must not duplicate the account prefix');
assert.equal(multiAccount.holdings.length,1,'same security across accounts is aggregated for portfolio comparison');
assert.equal(multiAccount.holdings[0].shares,5);
assert.deepEqual(multiAccount.holdings[0].accounts,['acct-1','acct-2']);
assert.equal(multiAccount.comparisons[0].difference,0);
assert.equal(buildTossSync({orders:[{...row,id:'legacy-id',accountId:'acct-1'}]},{existingTrades:[{source:{provider:'toss',externalId:'legacy-id'}}]}).candidates.length,0,'pre-account Toss ids remain duplicate-safe');
const linked=tossCandidateToDividend({id:'div-account',accountId:'acct-1',securityId:'US-MSTY',market:'NASDAQ',symbol:'MSTY',date:'2026-01-22',netAmount:9,currency:'USD'},{projectId:'p-msty',id:'d-account'});
assert.equal(linked.source.accountId,'acct-1');
assert.equal(linked.source.assetKey,'toss:NASDAQ:US-MSTY');
const officialOrder={orderId:'official-1',accountId:'acct-1',symbol:'MSTY',side:'BUY',status:'FILLED',currency:'USD',orderedAt:'2026-02-01T10:00:00+09:00',execution:{filledQuantity:'2.5',averageFilledPrice:'11.25',filledAmount:'28.125',commission:'0.12',tax:'0.03',filledAt:'2026-02-01T10:00:02+09:00',settlementDate:'2026-02-03'}};
const normalizedOfficial=normalizeTossOrder(officialOrder);
assert.equal(normalizedOfficial.shares,2.5);
assert.equal(normalizedOfficial.feeUSD,.12);
assert.equal(normalizedOfficial.taxUSD,.03);
const importedOfficial=tossCandidateToTrade(normalizedOfficial,{projectId:'p-msty',id:'t-official'});
assert.equal(importedOfficial.source.status,'FILLED');
assert.ok(importedOfficial.source.sourceFingerprint);
const correction=buildTossSync({orders:[{...officialOrder,execution:{...officialOrder.execution,averageFilledPrice:'11.5'}}]},{existingTrades:[importedOfficial]});
assert.equal(correction.candidates.length,0);
assert.equal(correction.correctionCandidates.length,1,'changed upstream execution must be reported without silently rewriting the ledger');
const voided=buildTossSync({orders:[{...officialOrder,status:'CANCELED',execution:{filledQuantity:'0',averageFilledPrice:null,filledAmount:null,commission:null,tax:null,filledAt:null,settlementDate:null}}]},{existingTrades:[importedOfficial]});
assert.equal(voided.correctionCandidates.length,1,'a later cancellation with zero filled quantity must still alert the user');
assert.equal(voided.correctionCandidates[0].changeType,'voided');
assert.equal(mergeTossCorrectionCandidates(voided.correctionCandidates,voided.correctionCandidates).length,1);
const noSourceId=normalizeTossOrder({symbol:'MSTY',accountId:'acct-1',date:'2026-02-02',side:'BUY',shares:1,price:12,currency:'USD'});
assert.equal(noSourceId.sourceIdKind,'fingerprint');
assert.equal(normalizeTossOrder(noSourceId).externalId,noSourceId.externalId,'fallback fingerprints must be stable across normalization');
assert.equal(nextTossSyncFrom({syncCursor:{ordersThrough:'2026-02-20'}},'2020-01-01'),'2026-02-06');
assert.equal(accountScopeChanged('abc','def'),true);
const partialProgress=tossSyncProgress({syncCursor:{ordersThrough:'2026-01-01'},lastSuccessfulAt:'old'},{syncStatus:'partial',failedAccountCount:1,fetchedAt:'new',syncCursor:{ordersThrough:'2026-02-01'}});
assert.equal(partialProgress.syncCursor.ordersThrough,'2026-01-01','failed accounts must not advance the incremental cursor');
assert.equal(partialProgress.lastSuccessfulAt,'old');
const priceOnlyPartial=tossSyncProgress({syncCursor:{ordersThrough:'2026-01-01'}},{syncStatus:'partial',failedAccountCount:0,fetchedAt:'new',syncCursor:{ordersThrough:'2026-02-01'}});
assert.equal(priceOnlyPartial.syncCursor.ordersThrough,'2026-02-01','a price-only failure must not force full order history next time');
const disconnected=disconnectedTossState({accountScopeId:'scope',sourceLedger:{orders:[{externalId:'x'}],dividends:[]},candidates:[row],holdings:[{}]});
assert.equal(disconnected.accountScopeId,'scope','disconnect keeps the account guard');
assert.equal(disconnected.sourceLedger.orders.length,1,'disconnect preserves source history');
assert.equal(disconnected.candidates.length,0);
console.log('Toss offline adapter: PASS (no account requests)');
